language: php

# php version to use for travis' composer & coverage
php:
  - 8.0

services:
  - docker

install:
  - travis_retry make install-php

script:
  - composer validate --no-interaction
  - make ci

after_success:
  - make ci-with-coverage COVERAGE_FLAGS="--coverage-clover coverage.clover"
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
